# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cmake -S . -B build
          cmake --build build
        

      - name: Testing
        run: |
          ./build/test/unittest
