# This is a basic workflow to help you get started with Actions

name: ExampleTest

on:
  push:
    branches: [master, new-python-tools]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Requirement
        run: |
          python3 -m pip install -r tools/requirements.txt

      - name: Build Source
        run: |
          python3 ./repo_manager.py -B --debug

      - name: Run Unittest
        run: |
          python3 ./repo_manager.py -r

