# This is a basic workflow to help you get started with Actions

name: ExampleTest

on:
  push:
    branches: [master, new-python-tools]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMakeLists.txt
        run: |
          cmake . -D CMAKE_BUILD_TYPE=Debug

      - name: Build Source
        run: |
          cmake --build .

      - name: Run Unittest
        run: |
          ./unittest

