name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMakeLists.txt
        run: |
          cmake . -DENABLE_LEETCODE_TEST=ON -DENABLE_INFRA_TEST=ON

      - name: Build Source
        run: |
          cmake --build .

      - name: Run Infra Test
        run: |
          ./infra_test

      - name: Run Leetcode Test
        run: |
          ./leetcode_test

